

# SystemVerilog support
USE_SLANG: True
SLANG_ARGUMENTS: ['--allow-use-before-declare', '--keep-hierarchy']

# Bondpad
# WARNING: You need to put the bondpads directly in the build folder
# You can find it at (https://github.com/IHP-GmbH/ihp-sg13g2-librelane-template/tree/main/ip)
PAD_BONDPAD_NAME: bondpad_70x70_novias
EXTRA_GDS:
- dir::ip/bondpad_70x70_novias/gds/bondpad_70x70_novias.gds
EXTRA_LEFS:
- dir::ip/bondpad_70x70_novias/lef/bondpad_70x70_novias.lef
IGNORE_DISCONNECTED_MODULES:
- bondpad_70x70_novias

# Power settings
PDN_CORE_RING: True
PDN_CORE_RING_CONNECT_TO_PADS: True     # Connect the pads to the core ring
PDN_ENABLE_PINS: False                  # We only need the PDK power pins
VDD_NETS:
- VDD
GND_NETS:
- VSS
# Connect SRAMS to PDN
PDN_MACRO_CONNECTIONS:
- "x_heep_system_inst.core_v_mini_mcu_i.memory_subsystem_i.ram0_i.genblk2.sram_inst VDD VSS VDDARRAY! VSS!"
- "x_heep_system_inst.core_v_mini_mcu_i.memory_subsystem_i.ram0_i.genblk2.sram_inst VDD VSS VDD! VSS!"
- "x_heep_system_inst.core_v_mini_mcu_i.memory_subsystem_i.ram1_i.genblk2.sram_inst VDD VSS VDDARRAY! VSS!"
- "x_heep_system_inst.core_v_mini_mcu_i.memory_subsystem_i.ram1_i.genblk2.sram_inst VDD VSS VDD! VSS!"

OPENROAD_THREADS: 32

# Pads
PAD_NORTH: [
  "x_heep_system_inst.pad_ring_i.u_pad_clk.pad_cell_input",
  "x_heep_system_inst.pad_ring_i.u_pad_rst.pad_cell_input",
  "x_heep_system_inst.pad_ring_i.u_pad_boot_select.pad_cell_input",
  "x_heep_system_inst.pad_ring_i.u_pad_execute_from_flash.pad_cell_input",
  "x_heep_system_inst.pad_ring_i.u_pad_jtag_tck.pad_cell_input",
  "x_heep_system_inst.pad_ring_i.u_pad_jtag_tms.pad_cell_input",
  "x_heep_system_inst.pad_ring_i.u_pad_jtag_trst.pad_cell_input",
  "x_heep_system_inst.pad_ring_i.u_pad_jtag_tdi.pad_cell_input",
  "x_heep_system_inst.pad_ring_i.u_pad_jtag_tdo.pad_cell_output",
  "x_heep_system_inst.pad_ring_i.u_pad_uart_rx.pad_cell_input",
  "x_heep_system_inst.pad_ring_i.u_pad_uart_tx.pad_cell_output",
  "x_heep_system_inst.pad_ring_i.u_pad_exit_valid.pad_cell_output",
  "x_heep_system_inst.pad_ring_i.u_pad_ddr_rcv_clk.pad_cell_input",
  "x_heep_system_inst.pad_ring_i.u_pad_ddr_snd_clk.pad_cell_output",
  "x_heep_system_inst.pad_ring_i.u_pad_gpio_0.pad_cell_inout",
  "x_heep_system_inst.pad_ring_i.u_pad_vdd0.pad_cell_vdd",
  "x_heep_system_inst.pad_ring_i.u_pad_vss0.pad_cell_vss",
]

PAD_WEST: [
  "x_heep_system_inst.pad_ring_i.u_pad_gpio_1.pad_cell_inout",
  "x_heep_system_inst.pad_ring_i.u_pad_gpio_2.pad_cell_inout",
  "x_heep_system_inst.pad_ring_i.u_pad_gpio_3.pad_cell_inout",
  "x_heep_system_inst.pad_ring_i.u_pad_gpio_4.pad_cell_inout",
  "x_heep_system_inst.pad_ring_i.u_pad_gpio_5.pad_cell_inout",
  "x_heep_system_inst.pad_ring_i.u_pad_gpio_6.pad_cell_inout",
  "x_heep_system_inst.pad_ring_i.u_pad_gpio_7.pad_cell_inout",
  "x_heep_system_inst.pad_ring_i.u_pad_gpio_8.pad_cell_inout",
  "x_heep_system_inst.pad_ring_i.u_pad_gpio_9.pad_cell_inout",
  "x_heep_system_inst.pad_ring_i.u_pad_gpio_10.pad_cell_inout",
  "x_heep_system_inst.pad_ring_i.u_pad_gpio_11.pad_cell_inout",
  "x_heep_system_inst.pad_ring_i.u_pad_gpio_12.pad_cell_inout",
  "x_heep_system_inst.pad_ring_i.u_pad_gpio_13.pad_cell_inout",
  "x_heep_system_inst.pad_ring_i.u_pad_spi_flash_sck.pad_cell_inout",
  "x_heep_system_inst.pad_ring_i.u_pad_spi_flash_cs_0.pad_cell_inout",
  "x_heep_system_inst.pad_ring_i.u_pad_iovdd0.pad_cell_iovdd",
  "x_heep_system_inst.pad_ring_i.u_pad_iovss0.pad_cell_iovss",
]

PAD_SOUTH: [
  "x_heep_system_inst.pad_ring_i.u_pad_vdd1.pad_cell_vdd",
  "x_heep_system_inst.pad_ring_i.u_pad_vss1.pad_cell_vss",
  "x_heep_system_inst.pad_ring_i.u_pad_spi_flash_cs_1.pad_cell_inout",
  "x_heep_system_inst.pad_ring_i.u_pad_spi_flash_sd_0.pad_cell_inout",
  "x_heep_system_inst.pad_ring_i.u_pad_spi_flash_sd_1.pad_cell_inout",
  "x_heep_system_inst.pad_ring_i.u_pad_spi_flash_sd_2.pad_cell_inout",
  "x_heep_system_inst.pad_ring_i.u_pad_spi_flash_sd_3.pad_cell_inout",
  "x_heep_system_inst.pad_ring_i.u_pad_spi_sck.pad_cell_inout",
  "x_heep_system_inst.pad_ring_i.u_pad_spi_cs_0.pad_cell_inout",
  "x_heep_system_inst.pad_ring_i.u_pad_spi_cs_1.pad_cell_inout",
  "x_heep_system_inst.pad_ring_i.u_pad_spi_sd_0.pad_cell_inout",
  "x_heep_system_inst.pad_ring_i.u_pad_spi_sd_1.pad_cell_inout",
  "x_heep_system_inst.pad_ring_i.u_pad_spi_sd_2.pad_cell_inout",
  "x_heep_system_inst.pad_ring_i.u_pad_spi_sd_3.pad_cell_inout",
  "x_heep_system_inst.pad_ring_i.u_pad_spi_slave_sck.pad_cell_input",
  "x_heep_system_inst.pad_ring_i.u_pad_spi_slave_cs.pad_cell_input",
  "x_heep_system_inst.pad_ring_i.u_pad_spi_slave_miso.pad_cell_inout",
]

PAD_EAST: [
  "x_heep_system_inst.pad_ring_i.u_pad_iovdd1.pad_cell_iovdd",
  "x_heep_system_inst.pad_ring_i.u_pad_iovss1.pad_cell_iovss",
  "x_heep_system_inst.pad_ring_i.u_pad_spi_slave_mosi.pad_cell_input",
  "x_heep_system_inst.pad_ring_i.u_pad_pdm2pcm_pdm.pad_cell_inout",
  "x_heep_system_inst.pad_ring_i.u_pad_pdm2pcm_clk.pad_cell_inout",
  "x_heep_system_inst.pad_ring_i.u_pad_i2s_sck.pad_cell_inout",
  "x_heep_system_inst.pad_ring_i.u_pad_i2s_ws.pad_cell_inout",
  "x_heep_system_inst.pad_ring_i.u_pad_i2s_sd.pad_cell_inout",
  "x_heep_system_inst.pad_ring_i.u_pad_spi2_cs_0.pad_cell_inout",
  "x_heep_system_inst.pad_ring_i.u_pad_spi2_cs_1.pad_cell_inout",
  "x_heep_system_inst.pad_ring_i.u_pad_spi2_sck.pad_cell_inout",
  "x_heep_system_inst.pad_ring_i.u_pad_spi2_sd_0.pad_cell_inout",
  "x_heep_system_inst.pad_ring_i.u_pad_spi2_sd_1.pad_cell_inout",
  "x_heep_system_inst.pad_ring_i.u_pad_spi2_sd_2.pad_cell_inout",
  "x_heep_system_inst.pad_ring_i.u_pad_spi2_sd_3.pad_cell_inout",
  "x_heep_system_inst.pad_ring_i.u_pad_i2c_scl.pad_cell_inout",
  "x_heep_system_inst.pad_ring_i.u_pad_i2c_sda.pad_cell_inout",
]

# SRAM Macros
MACROS:
  RM_IHPSG13_1P_256x32_c2_bm_bist:
    gds:
      - pdk_dir::libs.ref/sg13g2_sram/gds/RM_IHPSG13_1P_256x32_c2_bm_bist.gds
    lef:
      - pdk_dir::libs.ref/sg13g2_sram/lef/RM_IHPSG13_1P_256x32_c2_bm_bist.lef
    lib:
      "*_typ_1p20V_25C":
        - pdk_dir::libs.ref/sg13g2_sram/lib/RM_IHPSG13_1P_256x32_c2_bm_bist_typ_1p20V_25C.lib
      "*_fast_1p32V_m40C":
        - pdk_dir::libs.ref/sg13g2_sram/lib/RM_IHPSG13_1P_256x32_c2_bm_bist_fast_1p32V_m55C.lib
      "*_slow_1p08V_125C":
        - pdk_dir::libs.ref/sg13g2_sram/lib/RM_IHPSG13_1P_256x32_c2_bm_bist_slow_1p08V_125C.lib
  RM_IHPSG13_1P_512x32_c2_bm_bist:
    gds:
      - pdk_dir::libs.ref/sg13g2_sram/gds/RM_IHPSG13_1P_512x32_c2_bm_bist.gds
    lef:
      - pdk_dir::libs.ref/sg13g2_sram/lef/RM_IHPSG13_1P_512x32_c2_bm_bist.lef
    lib:
      "*_typ_1p20V_25C":
        - pdk_dir::libs.ref/sg13g2_sram/lib/RM_IHPSG13_1P_512x32_c2_bm_bist_typ_1p20V_25C.lib
      "*_fast_1p32V_m40C":
        - pdk_dir::libs.ref/sg13g2_sram/lib/RM_IHPSG13_1P_512x32_c2_bm_bist_fast_1p32V_m55C.lib
      "*_slow_1p08V_125C":
        - pdk_dir::libs.ref/sg13g2_sram/lib/RM_IHPSG13_1P_512x32_c2_bm_bist_slow_1p08V_125C.lib
  RM_IHPSG13_1P_1024x32_c2_bm_bist:
    gds:
      - pdk_dir::libs.ref/sg13g2_sram/gds/RM_IHPSG13_1P_1024x32_c2_bm_bist.gds
    lef:
      - pdk_dir::libs.ref/sg13g2_sram/lef/RM_IHPSG13_1P_1024x32_c2_bm_bist.lef
    lib:
      "*_typ_1p20V_25C":
        - pdk_dir::libs.ref/sg13g2_sram/lib/RM_IHPSG13_1P_1024x32_c2_bm_bist_typ_1p20V_25C.lib
      "*_fast_1p32V_m40C":
        - pdk_dir::libs.ref/sg13g2_sram/lib/RM_IHPSG13_1P_1024x32_c2_bm_bist_fast_1p32V_m55C.lib
      "*_slow_1p08V_125C":
        - pdk_dir::libs.ref/sg13g2_sram/lib/RM_IHPSG13_1P_1024x32_c2_bm_bist_slow_1p08V_125C.lib
  RM_IHPSG13_1P_8192x32_c4:
    gds:
      - pdk_dir::libs.ref/sg13g2_sram/gds/RM_IHPSG13_1P_8192x32_c4.gds
    lef:
      - pdk_dir::libs.ref/sg13g2_sram/lef/RM_IHPSG13_1P_8192x32_c4.lef
    lib:
      "*_typ_1p20V_25C":
        - pdk_dir::libs.ref/sg13g2_sram/lib/RM_IHPSG13_1P_8192x32_c4_typ_1p20V_25C.lib
      "*_fast_1p32V_m40C":
        - pdk_dir::libs.ref/sg13g2_sram/lib/RM_IHPSG13_1P_8192x32_c4_fast_1p32V_m55C.lib
      "*_slow_1p08V_125C":
        - pdk_dir::libs.ref/sg13g2_sram/lib/RM_IHPSG13_1P_8192x32_c4_slow_1p08V_125C.lib
